# Generated by Django 5.1.2 on 2024-11-18 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0003_group_members_alter_giftpreference_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftpreference',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_preferences', to='secret_santa.group'),
        ),
        migrations.AlterField(
            model_name='giftpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_gift_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
