# Generated by Django 5.1.2 on 2024-11-20 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0004_alter_giftpreference_group_alter_giftpreference_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gift_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
