# Generated by Django 5.1.2 on 2024-11-20 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0005_alter_giftpreference_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_secret_santa_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftpreference',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_preferences', to='secret_santa.group'),
        ),
    ]
