# Generated by Django 5.1.2 on 2024-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0007_group_group_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_rules',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
