# Generated by Django 5.1.2 on 2024-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0008_alter_group_group_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_rules',
            new_name='rules',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
